[project]
name = "experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.18.0",
    "polars>=1.35.2",
    "torch>=2.9.1",
]
